In [1]:
import numpy as np

In [2]:
arr=np.array([1,2,3,6,5,4])

In [3]:
rarr = arr[::-1]
print(rarr)

[4 5 6 3 2 1]


In [6]:
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[1,2,3],[4,5,6]])
print(arr1==arr2)

[[ True  True  True]
 [ True  True  True]]


In [10]:
x=np.array([1,2,3,4,5,1,2,1,1,1])
y=np.array([1,1,1,2,3,4,2,4,3,3])

mfreq_x=np.argmax(np.bincount(x))
mfreq_y=np.argmax(np.bincount(y))

print(mfreq_x, mfreq_y)

1 1


In [14]:
gfg=np.matrix('[4,1,9;12,3,1;4,5,6]')

In [19]:
print(gfg.sum(),'\n', gfg.sum(axis=1),'\n',gfg.sum(axis=0))

45 
 [[14]
 [16]
 [15]] 
 [[20  9 16]]
